### PR TITLE
Quick Sort Implementation

### PR DESCRIPTION
**Pull request by souvikbaruah**
C program to implement Quick Sort and count the basic number of steps executed.

### CODE REVIEW

**Review by drdeepakuniyal — CHANGES_REQUESTED** [review]
Your code seems hardcoded, so can you please generalize it.

**Comment by souvikbaruah** [comment]
The user can give any input. The user can also input the array size. The 'count' array taken is to count the number of times each step executed and it doesn't hardcode any value. Kindly check the code again, it isn't hardcoded! Thank you.

**Review by drdeepakuniyal — APPROVED** [review]
Yes, I got your point and the code. I am approving it but why you are trying to see which line executed how many times in Quicksort code? Is that really needed?

**Comment by souvikbaruah** [comment]
Thank you for accepting my PR. Actually, I was analyzing quick sort and counting the number of times each step executed helped to verify the analysis. This made it a unique program too as many people are submitting quick sort!

**Pull request merged**
